name: CI
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 3" # At 05:00 on Wednesday # https://crontab.guru/#0_5_*_*_3
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "*"

jobs:
  build_source_gem:
    name: build source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          working-directory: test/rcd_test
          bundler-cache: true

      - name: Build source gem
        run: |
          cd test/rcd_test/
          bundle exec rake gem

      - name: Upload source gem
        uses: actions/upload-artifact@v3
        with:
          name: gem-ruby
          path: test/rcd_test/pkg/rcd_test-?.?.?.gem # e.g. rcd_test-1.0.0.gem

  build_native_gem:
    name: build native
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: aarch64-linux-gnu
            alias:    aarch64-linux
          - platform: arm-linux-gnu
            alias:    arm-linux
          - platform: arm-linux-musl
          - platform: arm64-darwin
          - platform: jruby
          - platform: x64-mingw-ucrt
            static: true
          - platform: x64-mingw32
            static: true
          - platform: x86-linux-gnu
            alias:    x86-linux
          - platform: x86-linux-musl
          - platform: x86-mingw32
          - platform: x86_64-darwin
          - platform: x86_64-linux-gnu
            alias:    x86_64-linux
          - platform: x86_64-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Fetch docker buildx layer cache
        uses: actions/cache@v3
        with:
          path: tmp/build-cache
          key: ${{ runner.os }}-${{ matrix.platform }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.platform }}-buildx
      - name: Build docker image
        run: |
          docker buildx create --driver docker-container --use
          bundle exec rake build:${{ matrix.platform }} RCD_DOCKER_BUILD="docker buildx build --cache-from=type=local,src=tmp/build-cache --cache-to=type=local,dest=tmp/build-cache-new --load"
          docker images
      - name: Update and prune docker buildx layer cache
        run: |
          rm -rf tmp/build-cache
          mv tmp/build-cache-new tmp/build-cache

      - name: Test the generated image
        run: bundle exec rake test TEST_PLATFORM=${{ matrix.platform }}

      - name: Build native gem
        run: |
          cd test/rcd_test/
          bundle install
          bundle exec rake clean clobber
          bundle exec rake gem:${{ matrix.platform }}

      - name: Upload native gem
        uses: actions/upload-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
          path: test/rcd_test/pkg/*-*-*.gem

      - if: matrix.static
        name: Build static native gem
        env:
          RCD_TEST_CONFIG: "--link-static"
        run: |
          cd test/rcd_test/
          bundle install
          bundle exec rake clean clobber
          bundle exec rake gem:${{ matrix.platform }}

      - if: matrix.static
        name: Upload static native gem
        uses: actions/upload-artifact@v3
        with:
          name: gem-${{ matrix.platform }}-static
          path: test/rcd_test/pkg/*-*-*.gem

      - if: matrix.alias
        name: Build native gem ${{ matrix.alias }}
        run: |
          cd test/rcd_test/
          bundle install
          bundle exec rake clean clobber
          bundle exec rake gem:${{ matrix.alias }}

      - if: matrix.alias
        name: Upload native gem ${{ matrix.alias }}
        uses: actions/upload-artifact@v3
        with:
          name: gem-${{ matrix.alias }}
          path: test/rcd_test/pkg/*-*-*.gem

  test_source_gem:
    name: source gem
    needs: build_source_gem
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: ["3.3", "3.2", "3.1", "3.0", "2.7", "2.6", "2.5", "2.4"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Download source gem
        uses: actions/download-artifact@v3
        with:
          name: gem-ruby
      - name: Install source gem
        run: gem install --local *.gem --verbose
      - name: Test source gem
        run: |
          cd test/rcd_test/
          bundle install
          ruby -rrcd_test -S rake test

  test_x86_64-linux-gnu-in-setup-ruby:
    name: x86_64-linux-gnu setup-ruby
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.2", "3.1", "3.0", "2.7", "2.6", "2.5", "2.4"]
        platform: [x86_64-linux]
        include:
          # ruby 3.0 and earlier ship rubygems < 3.2.33, so can't recognize the -gnu suffix
          - ruby: "3.3"
            platform: x86_64-linux-gnu
          - ruby: "3.2"
            platform: x86_64-linux-gnu
          - ruby: "3.1"
            platform: x86_64-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Download gem-${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Install gem-${{ matrix.platform }}
        run: gem install --local *.gem --verbose
      - name: Run tests
        run: |
          cd test/rcd_test/
          bundle install
          ruby -rrcd_test -S rake test

  test_x86_64-linux-gnu-in-docker:
    name: x86_64-linux-gnu docker
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.2", "3.1", "3.0", "2.7", "2.6", "2.5", "2.4"]
        platform: [x86_64-linux]
        include:
          # ruby 3.0 and earlier ship rubygems < 3.2.33, so can't recognize the -gnu suffix
          - ruby: "3.3"
            platform: x86_64-linux-gnu
          - ruby: "3.2"
            platform: x86_64-linux-gnu
          - ruby: "3.1"
            platform: x86_64-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download gem-${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Run tests
        run: |
          docker run --rm -v $PWD:/work -w /work \
            ruby:${{ matrix.ruby }} \
            bash -c "
              gem install --local *.gem --verbose &&
              cd test/rcd_test/ &&
              bundle install &&
              ruby -rrcd_test -S rake test
            "

  test_x86_64-linux-musl:
    name: x86_64-linux-musl
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.2", "3.1", "3.0", "2.7"] # ruby:2.6-alpine and earlier ship with rubygems that doesn't recognize the -musl suffix
        platform: [x86_64-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download gem-${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Run tests
        run: |
          docker run --rm -v $PWD:/work -w /work \
            ruby:${{ matrix.ruby }}-alpine \
            sh -c "
              gem install --local *.gem --verbose &&
              cd test/rcd_test/ &&
              bundle install &&
              ruby -rrcd_test -S rake test
            "

  test_x86-linux-gnu:
    name: x86-linux-gnu
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.2", "3.1", "3.0", "2.7", "2.6", "2.5", "2.4"]
        platform: [x86-linux]
        include:
          # ruby 3.0 and earlier ship rubygems < 3.2.33, so can't recognize the -gnu suffix
          - ruby: "3.3"
            platform: x86-linux-gnu
          - ruby: "3.2"
            platform: x86-linux-gnu
          - ruby: "3.1"
            platform: x86-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download gem-${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Run tests
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v $PWD:/work -w /work \
            --platform=linux/386 ruby:${{ matrix.ruby }} \
            sh -c "
              gem install --local *.gem --verbose &&
              cd test/rcd_test/ &&
              bundle install &&
              ruby -rrcd_test -S rake test
            "

  test_x86-linux-musl:
    name: x86-linux-musl
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.2", "3.1", "3.0", "2.7"] # ruby:2.6-alpine and earlier ship with rubygems that doesn't recognize the -musl suffix
        platform: [x86-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download gem-${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Run tests
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v $PWD:/work -w /work \
            --platform=linux/386 ruby:${{ matrix.ruby }}-alpine \
            sh -c "
              gem install --local *.gem --verbose &&
              cd test/rcd_test/ &&
              bundle install &&
              ruby -rrcd_test -S rake test
            "

  test_arm-linux-gnu:
    name: arm-linux-gnu
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.2", "3.1", "3.0", "2.7", "2.6", "2.5", "2.4"]
        platform: [arm-linux]
        include:
          # ruby 3.0 and earlier ship rubygems < 3.2.33, so can't recognize the -gnu suffix
          - ruby: "3.3"
            platform: arm-linux-gnu
          - ruby: "3.2"
            platform: arm-linux-gnu
          - ruby: "3.1"
            platform: arm-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download gem-${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Run tests
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v $PWD:/work -w /work \
            --platform=linux/arm/v7 ruby:${{ matrix.ruby }} \
            sh -c "
              gem install --local *.gem --verbose &&
              cd test/rcd_test/ &&
              bundle install &&
              ruby -rrcd_test -S rake test
            "

  test_arm-linux-musl:
    name: arm-linux-musl
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.2", "3.1"] # TODO can we update rubygems and get earlier images working?
        platform: [arm-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download gem-${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Run tests
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v $PWD:/work -w /work \
            --platform=linux/arm/v7 ruby:${{ matrix.ruby }}-alpine \
            sh -c "
              gem install --local *.gem --verbose &&
              cd test/rcd_test/ &&
              bundle install &&
              ruby -rrcd_test -S rake test
            "

  test_native_gem:
    name: test native
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
          - "2.4"
        include:
          - os: macos
            platform: x86_64-darwin
          - os: ubuntu
            ruby: jruby
            platform: jruby
          - os: windows
            ruby: "2.4"
            platform: x64-mingw32
          - os: windows
            ruby: "2.5"
            platform: x64-mingw32
          - os: windows
            ruby: "2.6"
            platform: x64-mingw32
          - os: windows
            ruby: "2.7"
            platform: x64-mingw32
          - os: windows
            ruby: "3.0"
            platform: x64-mingw32
          - os: windows
            ruby: "3.1"
            platform: x64-mingw-ucrt
          - os: windows
            ruby: "3.2"
            platform: x64-mingw-ucrt
          - os: windows
            ruby: "3.3"
            platform: x64-mingw-ucrt
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Print ruby version and gem env
        run: |
          ruby --version
          gem env
      - name: Download gem-${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Install gem-${{ matrix.platform }}
        run: gem install --local *.gem --verbose
      - name: Run tests
        run: |
          cd test/rcd_test/
          bundle install
          ruby -rrcd_test -S rake test

  test_static_native_gem:
    name: test static
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            ruby: "2.4"
            platform: x64-mingw32
          - os: windows
            ruby: "2.5"
            platform: x64-mingw32
          - os: windows
            ruby: "2.6"
            platform: x64-mingw32
          - os: windows
            ruby: "2.7"
            platform: x64-mingw32
          - os: windows
            ruby: "3.0"
            platform: x64-mingw32
          - os: windows
            ruby: "3.1"
            platform: x64-mingw-ucrt
          - os: windows
            ruby: "3.2"
            platform: x64-mingw-ucrt
          - os: windows
            ruby: "3.3"
            platform: x64-mingw-ucrt
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Print ruby version and gem env
        run: |
          ruby --version
          gem env
      - name: Download gem-${{ matrix.platform }}-static
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}-static
      - name: Install gem-${{ matrix.platform }}-static
        run: gem install --local *.gem --verbose
      - name: Run tests
        run: |
          cd test/rcd_test/
          bundle install
          ruby -rrcd_test -S rake test

  test_native_gem_multiarch:
    name: ${{ matrix.platform }} on ${{ matrix.from_image }}
    needs: build_native_gem
    strategy:
      fail-fast: false
      matrix:
        include:
          - from_image: amd64/centos
            platform: x86_64-linux # centos-8 ships ruby 2.5, rubygems won't recognize -gnu suffix
            dockerfile: centos
          - from_image: navikey/raspbian-bullseye
            platform: arm-linux # bullseye ships ruby 2.7, rubygems won't recognize -gnu suffix
            dockerfile: debian
          - from_image: arm64v8/ubuntu
            platform: aarch64-linux # arm64v8 ships ruby 3.0, rubygems won't recognize -gnu suffix
            dockerfile: debian
          - from_image: i386/alpine
            platform: x86-linux-musl
            dockerfile: alpine
          - from_image: arm32v6/alpine
            platform: arm-linux-musl
            dockerfile: alpine
          - from_image: alpine
            platform: x86_64-linux-musl
            dockerfile: alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download gem-${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Build ${{ matrix.from_image }} image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker build --rm --build-arg from_image=${{ matrix.from_image }} -t ruby-test -f test/env/Dockerfile.${{ matrix.dockerfile }} .
      - name: Run tests
        run: docker run --rm -t --network=host -v `pwd`:/build ruby-test
